/**
 * 画面のテキストを検証する
 */
describe('適切にテキストが表示されているか', () => {
  it('タイトル表示', () => {
    cy.visit('http://localhost:3000')
    cy.contains('p', '都道県別総人口図表')
  })

  it('サブタイトル表示', () => {
    cy.visit('http://localhost:3000')
    cy.contains('p', '都道府県')
  })

  it('47都道府県チェックボックスのラベルが表示されているか', () => {
    cy.visit('http://localhost:3000')
    cy.contains('label', '北海道')
    cy.contains('label', '青森県')
    cy.contains('label', '岩手県')
    cy.contains('label', '宮城県')
    cy.contains('label', '秋田県')
    cy.contains('label', '山形県')
    cy.contains('label', '福島県')
    cy.contains('label', '茨城県')
    cy.contains('label', '栃木県')
    cy.contains('label', '群馬県')
    cy.contains('label', '埼玉県')
    cy.contains('label', '千葉県')
    cy.contains('label', '東京都')
    cy.contains('label', '神奈川県')
    cy.contains('label', '新潟県')
    cy.contains('label', '富山県')
    cy.contains('label', '石川県')
    cy.contains('label', '福井県')
    cy.contains('label', '山梨県')
    cy.contains('label', '長野県')
    cy.contains('label', '岐阜県')
    cy.contains('label', '静岡県')
    cy.contains('label', '愛知県')
    cy.contains('label', '三重県')
    cy.contains('label', '滋賀県')
    cy.contains('label', '京都府')
    cy.contains('label', '大阪府')
    cy.contains('label', '兵庫県')
    cy.contains('label', '奈良県')
    cy.contains('label', '和歌山県')
    cy.contains('label', '鳥取県')
    cy.contains('label', '島根県')
    cy.contains('label', '岡山県')
    cy.contains('label', '広島県')
    cy.contains('label', '山口県')
    cy.contains('label', '徳島県')
    cy.contains('label', '香川県')
    cy.contains('label', '愛媛県')
    cy.contains('label', '高知県')
    cy.contains('label', '福岡県')
    cy.contains('label', '佐賀県')
    cy.contains('label', '長崎県')
    cy.contains('label', '熊本県')
    cy.contains('label', '大分県')
    cy.contains('label', '宮崎県')
    cy.contains('label', '鹿児島県')
    cy.contains('label', '沖縄県')
  })
})
